Livechat.create(text:'テストです〜〜')
Livechat.create(text:'回線が不安定だ〜〜')
Livechat.create(text:'始めて見に来ました〜〜')
Livechat.create(text:'声が小さくて聞き取り辛いです・・・')
Livechat.create(text:'もう少しゆっくり話して欲しいですm(_ _)m')
Livechat.create(text:'プログラミングが楽しくなってきました♫')
